name: Demo GitHub actions
on: [push]

jobs:
  Explore-Actions-Github:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}